workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      groups:
        - Apple Credentials
      xcode: latest
      cocoapods: default
      flutter: stable
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.h24consulting.appariteur"

    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build
        script: |
          flutter build ipa --export-options-plist=ios/exportOptions.plist